<a href="https://colab.research.google.com/github/helah20/Machine_learning/blob/main/Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd   # import pandas 
df=pd.read_csv('https://raw.githubusercontent.com/gumdropsteve/intro_to_machine_learning/main/day_04/data/dammam.csv')  #UPLOAD CSVfiles

##  Exploring the dataset

In [3]:
df.head()

                           ds  ... chefs_kitchen_bool
0  2021-01-20 03:52:47.315742  ...                NaN
1  2021-01-20 03:52:47.315742  ...                NaN
2  2021-01-20 03:52:47.315742  ...                NaN
3  2021-01-20 03:52:47.315742  ...                NaN
4  2021-01-20 03:52:47.315742  ...                NaN

[5 rows x 40 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1626 entries, 0 to 1625
Data columns (total 40 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ds                       1626 non-null   object
 1   search_filter            1076 non-null   object
 2   url                      1626 non-null   object
 3   title                    1626 non-null   object
 4   type                     1626 non-null   object
 5   location                 1626 non-null   object
 6   guests                   1021 non-null   float64
 7   bedrooms                 1626 non-null   int64
 8   beds                     1021 non-null   float64
 9   is_studio                1626 non-null   bool
 10  baths                    1126 non-null   float64
 11  half_baths               0 non-null      float64
 12  shared_baths             10 non-null     float64
 13  price                    1626 non-null   float64
 14  avg_rating               515 non-null    float64
 15  n_reviews                515 non-null    float64
 16  gym_bool                 176 non-null    object
 17  wifi_bool                647 non-null    object
 18  self_check_in_bool       103 non-null    object
 19  air_conditioning_bool    961 non-null    object
 20  pets_allowed_bool        86 non-null     object
 21  indoor_fireplace_bool    21 non-null     object
 22  hot_tub_bool             25 non-null     object
 23  free_parking_bool        494 non-null    object
 24  pool_bool                233 non-null    object
 25  kitchen_bool             607 non-null    object
 26  breakfast_bool           107 non-null    object
 27  elevator_bool            235 non-null    object
 28  washer_bool              82 non-null     object
 29  dryer_bool               31 non-null     object
 30  heating_bool             0 non-null      float64
 31  waterfront_bool          31 non-null     object
 32  dishwasher_bool          0 non-null      float64
 33  beachfront_bool          24 non-null     object
 34  ski_in_ski_out_bool      7 non-null      object
 35  terrace_bool             0 non-null      float64
 36  sonos_sound_system_bool  0 non-null      float64
 37  bbq_grill_bool           0 non-null      float64
 38  hair_dryer_bool          0 non-null      float64
 39  chefs_kitchen_bool       0 non-null      float64
dtypes: bool(1), float64(15), int64(1), object(23)
memory usage: 497.1+ KB

In [43]:
df.isna().sum() # there is alot of null values we can

ds                            0
search_filter               550
url                           0
title                         0
type                          0
location                      0
guests                      605
bedrooms                      0
beds                        605
is_studio                     0
baths                       500
half_baths                 1626
shared_baths               1616
price                         0
avg_rating                 1111
n_reviews                  1111
gym_bool                   1450
wifi_bool                   979
self_check_in_bool         1523
air_conditioning_bool       665
pets_allowed_bool          1540
indoor_fireplace_bool      1605
hot_tub_bool               1601
free_parking_bool          1132
pool_bool                  1393
kitchen_bool               1019
breakfast_bool             1519
elevator_bool              1391
washer_bool                1544
dryer_bool                 1595
heating_bool               1626
waterfront_bool            1595
dishwasher_bool            1626
beachfront_bool            1602
ski_in_ski_out_bool        1619
terrace_bool               1626
sonos_sound_system_bool    1626
bbq_grill_bool             1626
hair_dryer_bool            1626
chefs_kitchen_bool         1626
dtype: int64

# **fillin na with mean using pandas**

In [65]:
df = pd.DataFrame(df)

df.fillna(df['beds'].mean())

     search_filter  ... chefs_kitchen_bool
0          2.47209  ...           2.472086
1          2.47209  ...           2.472086
2          2.47209  ...           2.472086
3          2.47209  ...           2.472086
4          2.47209  ...           2.472086
...            ...  ...                ...
1621  shared_rooms  ...           2.472086
1622  shared_rooms  ...           2.472086
1623  shared_rooms  ...           2.472086
1624  shared_rooms  ...           2.472086
1625  shared_rooms  ...           2.472086

[1626 rows x 38 columns]

In [5]:
df.describe() # alot of NaN , we need to drop some unnessesery  coloumns

            guests     bedrooms  ...  hair_dryer_bool  chefs_kitchen_bool
count  1021.000000  1626.000000  ...              0.0                 0.0
mean      2.472086     1.412669  ...              NaN                 NaN
std       1.806973     1.925712  ...              NaN                 NaN
min       0.000000     0.000000  ...              NaN                 NaN
25%       2.000000     1.000000  ...              NaN                 NaN
50%       2.000000     1.000000  ...              NaN                 NaN
75%       3.000000     2.000000  ...              NaN                 NaN
max      14.000000    50.000000  ...              NaN                 NaN

[8 rows x 16 columns]

In [49]:
df.drop(['heating_bool','dishwasher_bool', 'terrace_bool','sonos_sound_system_bool','bbq_grill_bool','hair_dryer_bool','chefs_kitchen_bool'],  axis = 1)

                              ds  ... ski_in_ski_out_bool
0     2021-01-20 03:52:47.315742  ...                 NaN
1     2021-01-20 03:52:47.315742  ...                 NaN
2     2021-01-20 03:52:47.315742  ...                 NaN
3     2021-01-20 03:52:47.315742  ...                 NaN
4     2021-01-20 03:52:47.315742  ...                 NaN
...                          ...  ...                 ...
1621  2021-01-26 05:07:39.107916  ...                 NaN
1622  2021-01-26 05:07:39.107916  ...                 NaN
1623  2021-01-26 05:07:39.107916  ...                 NaN
1624  2021-01-26 05:07:39.107916  ...                 NaN
1625  2021-01-26 05:07:39.107916  ...                 NaN

[1626 rows x 33 columns]

we want here to explore the ds column

In [6]:
df.ds.unique()

array(['2021-01-20 03:52:47.315742', '2021-01-20 03:52:48.889809',
       '2021-01-20 03:52:51.021932', '2021-01-20 03:52:54.977167',
       '2021-01-20 03:52:57.767468', '2021-01-20 03:52:59.247350',
       '2021-01-20 03:53:03.785655', '2021-01-20 03:53:06.832059',
       '2021-01-20 03:53:09.011312', '2021-01-20 03:53:10.720817',
       '2021-01-20 03:53:14.249472', '2021-01-20 03:53:15.947138',
       '2021-01-20 03:53:20.800041', '2021-01-20 03:53:22.960469',
       '2021-01-20 03:53:26.508008', '2021-01-20 03:53:28.818406',
       '2021-01-20 03:53:32.103904', '2021-01-20 03:53:34.468558',
       '2021-01-20 03:53:38.741260', '2021-01-20 03:53:40.945372',
       '2021-01-21 04:32:51.875555', '2021-01-21 04:32:53.006103',
       '2021-01-21 04:32:55.388227', '2021-01-21 04:32:56.954055',
       '2021-01-21 04:32:59.054961', '2021-01-22 07:12:42.839610',
       '2021-01-22 07:12:45.275081', '2021-01-22 07:12:46.661258',
       '2021-01-22 07:12:48.182166', '2021-01-22 07:12:49.637255',
       '2021-01-22 07:12:51.409183', '2021-01-22 07:12:52.479779',
       '2021-01-22 07:12:53.933984', '2021-01-22 07:12:55.956658',
       '2021-01-22 07:12:57.221657', '2021-01-22 07:12:58.812564',
       '2021-01-22 07:13:00.262782', '2021-01-22 07:13:02.252554',
       '2021-01-23 17:08:51.760444', '2021-01-23 17:08:53.901489',
       '2021-01-23 17:08:56.186975', '2021-01-23 17:08:58.034282',
       '2021-01-23 17:08:59.662359', '2021-01-23 17:09:01.644093',
       '2021-01-23 17:09:03.876083', '2021-01-23 17:09:06.119682',
       '2021-01-23 17:09:07.839606', '2021-01-23 17:09:09.671879',
       '2021-01-23 17:09:11.252661', '2021-01-23 17:09:13.308126',
       '2021-01-23 17:09:14.653525', '2021-01-23 17:09:17.691719',
       '2021-01-23 17:09:19.382402', '2021-01-23 17:09:22.483579',
       '2021-01-23 17:09:24.484363', '2021-01-25 04:32:22.838211',
       '2021-01-25 04:32:26.333515', '2021-01-25 04:32:28.737338',
       '2021-01-25 04:32:31.696454', '2021-01-25 04:32:35.158412',
       '2021-01-25 04:32:39.812069', '2021-01-25 04:32:42.830589',
       '2021-01-25 04:32:45.581329', '2021-01-25 04:32:48.950119',
       '2021-01-25 04:32:51.852682', '2021-01-25 04:32:54.494183',
       '2021-01-25 04:32:57.853258', '2021-01-25 04:33:00.237012',
       '2021-01-25 04:33:04.269550', '2021-01-25 04:33:06.453238',
       '2021-01-25 04:33:08.432700', '2021-01-25 04:33:12.768903',
       '2021-01-25 04:33:15.856555', '2021-01-25 04:33:20.725838',
       '2021-01-25 04:33:23.670839', '2021-01-26 05:06:41.817663',
       '2021-01-26 05:06:45.207526', '2021-01-26 05:06:48.371830',
       '2021-01-26 05:06:51.225030', '2021-01-26 05:06:54.233531',
       '2021-01-26 05:06:56.532634', '2021-01-26 05:06:59.839409',
       '2021-01-26 05:07:03.339848', '2021-01-26 05:07:06.925475',
       '2021-01-26 05:07:12.969105', '2021-01-26 05:07:15.835215',
       '2021-01-26 05:07:19.278675', '2021-01-26 05:07:21.055015',
       '2021-01-26 05:07:26.847255', '2021-01-26 05:07:30.280472',
       '2021-01-26 05:07:35.229728', '2021-01-26 05:07:39.107916'],
      dtype=object)

In [7]:
df.ds.str.split(expand=True)[0]

0       2021-01-20
1       2021-01-20
2       2021-01-20
3       2021-01-20
4       2021-01-20
           ...
1621    2021-01-26
1622    2021-01-26
1623    2021-01-26
1624    2021-01-26
1625    2021-01-26
Name: 0, Length: 1626, dtype: object

In [8]:
df.ds.str.split(expand=True)[0].unique()

array(['2021-01-20', '2021-01-21', '2021-01-22', '2021-01-23',
       '2021-01-25', '2021-01-26'], dtype=object)

**now we want to explor the type coulmn **

In [10]:
df['type']

0       Entire apartment
1       Entire apartment
2       Entire apartment
3       Entire apartment
4       Entire apartment
              ...
1621        Private room
1622       Entire chalet
1623         Entire loft
1624                Room
1625        Private room
Name: type, Length: 1626, dtype: object

In [11]:
len(df['type'].unique()) #  we have 16 type in the dataset

16

In [12]:

df['type'].value_counts() # it seems Categorical Features

Entire apartment             577
Private room                 457
Entire serviced apartment    138
Room                         110
Entire chalet                 50
Shared room                   48
Hotel room                    41
Entire house                  35
Entire loft                   32
Entire place                  26
Entire bungalow               25
Farm stay                     24
Camper/RV                     22
Entire villa                  15
Entire townhouse              15
Earth house                   11
Name: type, dtype: int64

In [13]:

# overall, we want to predict price
df['price']

0       145.0
1        96.0
2        87.0
3       120.0
4       121.0
        ...
1621    167.0
1622    533.0
1623    107.0
1624    133.0
1625     51.0
Name: price, Length: 1626, dtype: float64

In [17]:

d = [{'type':v} for v in df.type]
d

[{'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire house'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire house'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Camper/RV'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire house'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Farm stay'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire place'},
 {'type': 'Room'},
 {'type': 'Entire place'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire townhouse'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire villa'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Earth house'},
 {'type': 'Hotel room'},
 {'type': 'Private room'},
 {'type': 'Farm stay'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Private room'},
 {'type': 'Entire loft'},
 {'type': 'Entire house'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire house'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Camper/RV'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire house'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire place'},
 {'type': 'Room'},
 {'type': 'Entire place'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire townhouse'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire villa'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Earth house'},
 {'type': 'Hotel room'},
 {'type': 'Private room'},
 {'type': 'Farm stay'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Camper/RV'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire house'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire place'},
 {'type': 'Entire place'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire townhouse'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire chalet'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Entire villa'},
 {'type': 'Hotel room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Entire loft'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Camper/RV'},
 {'type': 'Shared room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire house'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Camper/RV'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire loft'},
 {'type': 'Entire loft'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Entire house'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Entire townhouse'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Camper/RV'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire house'},
 {'type': 'Entire chalet'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Farm stay'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Farm stay'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire place'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Room'},
 {'type': 'Entire place'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire villa'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Earth house'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Hotel room'},
 {'type': 'Private room'},
 {'type': 'Farm stay'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire house'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Camper/RV'},
 {'type': 'Room'},
 {'type': 'Entire loft'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire house'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Farm stay'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Farm stay'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire place'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire place'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire chalet'},
 {'type': 'Entire apartment'},
 {'type': 'Entire villa'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Earth house'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Hotel room'},
 {'type': 'Private room'},
 {'type': 'Farm stay'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire house'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Camper/RV'},
 {'type': 'Entire townhouse'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Private room'},
 {'type': 'Entire house'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Entire house'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Farm stay'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire place'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Room'},
 {'type': 'Entire place'},
 {'type': 'Private room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Shared room'},
 {'type': 'Entire serviced apartment'},
 {'type': 'Entire villa'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Earth house'},
 {'type': 'Hotel room'},
 {'type': 'Private room'},
 {'type': 'Farm stay'},
 {'type': 'Entire chalet'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire loft'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Entire apartment'},
 {'type': 'Shared room'},
 {'type': 'Room'},
 {'type': 'Entire house'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Camper/RV'},
 {'type': 'Room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Entire loft'},
 {'type': 'Entire apartment'},
 {'type': 'Private room'},
 {'type': 'Private room'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire bungalow'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},
 {'type': 'Entire apartment'},

In [67]:

from sklearn.feature_extraction import DictVectorizer  #  transformer turns lists of mappings (dict-like objects) of feature names to feature values  for use with scikit-learn estimators.

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

vec.fit_transform(data)[0]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
vec.feature_names_

['type=Camper/RV',
 'type=Earth house',
 'type=Entire apartment',
 'type=Entire bungalow',
 'type=Entire chalet',
 'type=Entire house',
 'type=Entire loft',
 'type=Entire place',
 'type=Entire serviced apartment',
 'type=Entire townhouse',
 'type=Entire villa',
 'type=Farm stay',
 'type=Hotel room',
 'type=Private room',
 'type=Room',
 'type=Shared room']

In [72]:
vec.fit_transform(data)[3:15]

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
pd.DataFrame(df['type'])

                  type
0     Entire apartment
1     Entire apartment
2     Entire apartment
3     Entire apartment
4     Entire apartment
...                ...
1621      Private room
1622     Entire chalet
1623       Entire loft
1624              Room
1625      Private room

[1626 rows x 1 columns]

In [73]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

t = vec.fit_transform(data)
names = vec.feature_names_

pd.DataFrame(t, columns=names)

      type=Camper/RV  type=Earth house  ...  type=Room  type=Shared room
0                  0                 0  ...          0                 0
1                  0                 0  ...          0                 0
2                  0                 0  ...          0                 0
3                  0                 0  ...          0                 0
4                  0                 0  ...          0                 0
...              ...               ...  ...        ...               ...
1621               0                 0  ...          0                 0
1622               0                 0  ...          0                 0
1623               0                 0  ...          0                 0
1624               0                 0  ...          1                 0
1625               0                 0  ...          0                 0

[1626 rows x 16 columns]

In [24]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.location]

t = vec.fit_transform(data)
names = vec.feature_names_

pd.DataFrame(t, columns=names)

      type=Al Eker  type=Al Khobar  ...  type=الدمام‎  type=المنامة
0                0               1  ...             0             0
1                0               1  ...             0             0
2                0               1  ...             0             0
3                0               0  ...             0             0
4                0               1  ...             0             0
...            ...             ...  ...           ...           ...
1621             0               1  ...             0             0
1622             0               1  ...             0             0
1623             0               0  ...             0             0
1624             0               0  ...             0             0
1625             0               0  ...             0             0

[1626 rows x 28 columns]

In [25]:
pd.get_dummies(df['type'])

      Camper/RV  Earth house  Entire apartment  ...  Private room  Room  Shared room
0             0            0                 1  ...             0     0            0
1             0            0                 1  ...             0     0            0
2             0            0                 1  ...             0     0            0
3             0            0                 1  ...             0     0            0
4             0            0                 1  ...             0     0            0
...         ...          ...               ...  ...           ...   ...          ...
1621          0            0                 0  ...             1     0            0
1622          0            0                 0  ...             0     0            0
1623          0            0                 0  ...             0     0            0
1624          0            0                 0  ...             0     1            0
1625          0            0                 0  ...             1     0            0

[1626 rows x 16 columns]

In [26]:

pd.get_dummies(df['type']).head(), df['type'].head()

(   Camper/RV  Earth house  Entire apartment  ...  Private room  Room  Shared room
 0          0            0                 1  ...             0     0            0
 1          0            0                 1  ...             0     0            0
 2          0            0                 1  ...             0     0            0
 3          0            0                 1  ...             0     0            0
 4          0            0                 1  ...             0     0            0

 [5 rows x 16 columns], 0    Entire apartment
 1    Entire apartment
 2    Entire apartment
 3    Entire apartment
 4    Entire apartment
 Name: type, dtype: object)

In [27]:
pd.get_dummies(df['type']).tail(), df['type'].tail()

(      Camper/RV  Earth house  Entire apartment  ...  Private room  Room  Shared room
 1621          0            0                 0  ...             1     0            0
 1622          0            0                 0  ...             0     0            0
 1623          0            0                 0  ...             0     0            0
 1624          0            0                 0  ...             0     1            0
 1625          0            0                 0  ...             1     0            0

 [5 rows x 16 columns], 1621     Private room
 1622    Entire chalet
 1623      Entire loft
 1624             Room
 1625     Private room
 Name: type, dtype: object)

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
X = vec.fit_transform(df.title)

pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

      13  2bed  31  700  800  abukhadra  ...  وصالة  وصاله  ومسبح  ومطبخ  وهادي  يوم
0      0     0   0    0    0          0  ...      0      0      0      0      0    0
1      0     0   0    0    0          0  ...      0      0      0      0      0    0
2      0     0   0    0    0          0  ...      0      0      0      0      0    0
3      0     0   0    0    0          0  ...      0      0      0      0      0    0
4      0     0   0    0    0          0  ...      0      0      0      0      0    0
...   ..   ...  ..  ...  ...        ...  ...    ...    ...    ...    ...    ...  ...
1621   0     0   0    0    0          0  ...      0      0      0      0      0    0
1622   0     0   0    0    0          0  ...      0      0      0      0      0    0
1623   0     0   0    0    0          0  ...      0      0      0      0      0    0
1624   0     0   0    0    0          0  ...      0      0      0      0      0    0
1625   0     0   0    0    0          0  ...      0      0      0      0      0    0

[1626 rows x 356 columns]

In [30]:

import numpy as np

np.sum(pd.DataFrame(X.toarray(), columns=vec.get_feature_names()))

13       11
2bed      2
31       56
700      14
800       1
         ..
وصاله    11
ومسبح     3
ومطبخ    11
وهادي    12
يوم      11
Length: 356, dtype: int64

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
sample = df['title']

vec = TfidfVectorizer()

X = vec.fit_transform(sample)

pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

       13  2bed   31  700  800  ...  وصاله  ومسبح  ومطبخ  وهادي  يوم
0     0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1     0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
2     0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
3     0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
4     0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
...   ...   ...  ...  ...  ...  ...    ...    ...    ...    ...  ...
1621  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1622  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1623  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1624  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1625  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0

[1626 rows x 356 columns]

In [32]:
t = pd.DataFrame()

t['price_per_bed'] = df['beds'] / df['price']

t

      price_per_bed
0          0.020690
1          0.062500
2               NaN
3               NaN
4          0.016529
...             ...
1621            NaN
1622       0.016886
1623       0.028037
1624       0.030075
1625            NaN

[1626 rows x 1 columns]

In [33]:
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(sparse=False, dtype=int)

# get list of dicts from `type` column
data = [{'type':v} for v in df.type]

d = vec.fit_transform(data)

type_df = pd.DataFrame(d, columns=vec.feature_names_)
type_df.tail(3)

      type=Camper/RV  type=Earth house  ...  type=Room  type=Shared room
1623               0                 0  ...          0                 0
1624               0                 0  ...          1                 0
1625               0                 0  ...          0                 0

[3 rows x 16 columns]

In [34]:
sample = df['title']

vec = TfidfVectorizer()

X = vec.fit_transform(sample)

tfidf_df = pd.DataFrame(X.toarray(), columns=vec.get_feature_names())
tfidf_df.tail(3)

       13  2bed   31  700  800  ...  وصاله  ومسبح  ومطبخ  وهادي  يوم
1623  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1624  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0
1625  0.0   0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0  0.0

[3 rows x 356 columns]

In [35]:

big_df = pd.concat([df, type_df, tfidf_df], axis=1)

big_df

                              ds search_filter  ... وهادي  يوم
0     2021-01-20 03:52:47.315742           NaN  ...   0.0  0.0
1     2021-01-20 03:52:47.315742           NaN  ...   0.0  0.0
2     2021-01-20 03:52:47.315742           NaN  ...   0.0  0.0
3     2021-01-20 03:52:47.315742           NaN  ...   0.0  0.0
4     2021-01-20 03:52:47.315742           NaN  ...   0.0  0.0
...                          ...           ...  ...   ...  ...
1621  2021-01-26 05:07:39.107916  shared_rooms  ...   0.0  0.0
1622  2021-01-26 05:07:39.107916  shared_rooms  ...   0.0  0.0
1623  2021-01-26 05:07:39.107916  shared_rooms  ...   0.0  0.0
1624  2021-01-26 05:07:39.107916  shared_rooms  ...   0.0  0.0
1625  2021-01-26 05:07:39.107916  shared_rooms  ...   0.0  0.0

[1626 rows x 412 columns]

In [39]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = df.drop(['price', 'ds'], axis=1)
y = df.price

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=7)

In [41]:
X_train

                search_filter  ... chefs_kitchen_bool
1021                      NaN  ...                NaN
830              entire_homes  ...                NaN
128              entire_homes  ...                NaN
1623             shared_rooms  ...                NaN
361                       NaN  ...                NaN
...                       ...  ...                ...
1603             shared_rooms  ...                NaN
502                       NaN  ...                NaN
537               super_hosts  ...                NaN
1220  entire_home_super_hosts  ...                NaN
175              entire_homes  ...                NaN

[1300 rows x 38 columns]

In [42]:
y_train

1021    504.0
830     270.0
128      26.0
1623    107.0
361      27.0
        ...
1603     25.0
502     208.0
537     120.0
1220    504.0
175     107.0
Name: price, Length: 1300, dtype: float64

In [40]:
lr = LinearRegression()

lr.fit(X_train, y_train)

ValueError: ignored